name: Mobile Goodness
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21073
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f7fd'
    - '#1d1f1e'
    - '#b24a15'
    - '#f7a714'
    - '#d311fd'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5452093193307519
purpose: []
